# Generated by Django 3.2 on 2022-03-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
        ('recipes', '0002_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourites',
            field=models.ManyToManyField(related_name='recipe_favourites', to='profiles.Profile'),
        ),
    ]
